# FUN WITH NUMPY OPERATIONS

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

<IPython.core.display.Javascript object>

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Uploading notebook to https://jovian.ml/imakshit/numpy-array-operations


<IPython.core.display.Javascript object>

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [7]:
# List of functions explained 

#function1 = np.prod()
#function2 = np.ones()
#function3 = ndArray.flatten()
#function4 = np.transpose()
#function5 = np.eye()

## Function 1 - np.prod()

Returns the product of elements of an array

In [8]:
# Example 1 
x = np.array([510, 560, 5368, 536])

np.prod(x)

821742028800

np.prod() returns the product of elements of array

In [9]:
# Example 2 - working
x = np.array([2,4,6])
np.prod(x, initial = 4)


192

You can also start the product with a value other than 1

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
#No case in which the function breaks
#will only break if any syntax error or argument missing

# I will explain a similar function instead of breaking condition

x = np.array([1,2,3,4,5])
np.ndarray.prod(x)


120

ndarray.prod() is similar to np.prod() function and returns the product of array elements

This function can be useful to compute the product of elements of an array


In [11]:
jovian.commit(project = "Assignment-2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/imakshit/Assignment-2


<IPython.core.display.Javascript object>

## Function 2 - np.ones()

Returns an array of one's with given size and shape

In [12]:
# Example 1 - working
np.ones(5)

array([1., 1., 1., 1., 1.])

Returns an array of size 5

In [13]:
# Example 2 - working
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Returns an 3x5 array of one's

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
# No case in which function breaks
# will only break if any syntax array or any argument missing
# I will explain some more concepts regarding this function here

np.ones((5,2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

User can specify the desired data type for the array

user can use it to get Array of ones with the given shape, dtype, and order.

In [15]:
jovian.commit(project = "Assignment-2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/imakshit/Assignment-2


<IPython.core.display.Javascript object>

## Function 3 - ndArray.flatten()
Return a copy of the array collapsed into one dimension

In [16]:
# Example 1 - working
arr = np.array([[1,2],[89,98],[45,68]])
arr.flatten()

array([ 1,  2, 89, 98, 45, 68])

returns a copy of arr in 1-dimensions

In [17]:
# Example 2 - working
x = np.array([[2,3],[4,5]])
x.flatten()

array([2, 3, 4, 5])

returns a copy of x in 1-dimensions

In [18]:
# Example 3 - breaking (to illustrate when it breaks)
# No case in which function breaks
# will only break if any syntax array or any argument missing
# I will explain some more concepts regarding this function here


#you can provide the optional argument 'order' to flatten the array in a specific order

# we will flatten in column-major
x.flatten('F')

array([2, 4, 3, 5])

order{‘C’, ‘F’, ‘A’, ‘K’}
‘C’ means to flatten in row-major (C-style) order. ‘F’ means to flatten in column-major (Fortran- style) order. ‘A’ means to flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise. ‘K’ means to flatten a in the order the elements occur in memory. The default is ‘C’.

we can use this function to create a copy of array in 1 dimensions

In [19]:
jovian.commit(project = "Assignment-2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/imakshit/Assignment-2


<IPython.core.display.Javascript object>

## Function 4 - np.transpose()
We can generate the transposition of an array using the tool numpy.transpose().
It will not affect the original array, but it will create a new array.

In [20]:
# Example 1 - working

my_array = np.array([[1,2,3],
                        [4,5,6]])
print("transposed array : ")
print(np.transpose(my_array))
print("original array : ")
print(my_array)


transposed array : 
[[1 4]
 [2 5]
 [3 6]]
original array : 
[[1 2 3]
 [4 5 6]]


returns transpose of array without affecting the original array

In [21]:
# Example 2 - working
x = np.arange(9).reshape((3,3))
print("transposed array: ")
print(np.transpose(x))
print("original array: ")
print(x)

transposed array: 
[[0 3 6]
 [1 4 7]
 [2 5 8]]
original array: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Explanation about example

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
# No case in which function breaks
# will only break if any syntax array or any argument missing
# I will explain some more concepts regarding this function here

x = np.ones((2,1,3))
print(x.shape)
y = np.transpose(x,(2,0,1)).shape
print(y)

(2, 1, 3)
(3, 2, 1)


Use transpose(a, argsort(axes)) to invert the transposition of tensors when using the axes keyword argument.

This function can be used to calculate transpose of a matrix

In [23]:
jovian.commit(project = "Assignment-2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/imakshit/Assignment-2


<IPython.core.display.Javascript object>

## Function 5 - np.eye()

The eye tool returns a 2-D array with 's as the diagonal and 's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter . A positive  is for the upper diagonal, a negative  is for the lower, and a   (default) is for the main diagonal.

In [24]:
# Example 1 - working
np.eye(8,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

returns an 8x7 array with diagonal as 1

In [25]:
# Example 2 - working
np.eye(8,8,k=2)

array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

returns an array with diagonal as 1 starting from index 2

In [26]:
# Example 3 - breaking (to illustrate when it breaks)
# No case in which function breaks
# will only break if any syntax array or any argument missing
# I will explain some more concepts regarding this function here

np.eye(8,8,10)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

If the value of 'K' is out of range, the function will simply return an array of zeroes with given dimensions


This function can be used to generate inverse of identity array

In [27]:
jovian.commit(project = "Assignment-2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/imakshit/Assignment-2


<IPython.core.display.Javascript object>

## Conclusion

We covered the following functions in the notebook - 
1. np.prod()
2. np.ones()
3. ndArray.flatten()
4. np.transpose()
5. np.eye()

I explained when the function will break and I explained a few more concepts regarding the function.
Hope you enjoyed going through the notebook.

For more practice on using numpy, you can solve questions on HackerRank. [click here](https://www.hackerrank.com/domains/python?badge_type=python&filters%5Bsubdomains%5D%5B%5D=numpy)


## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* HackerRank python questions on numpy : https://www.hackerrank.com/domains/python?badge_type=python&filters%5Bsubdomains%5D%5B%5D=numpy

In [29]:
jovian.commit(project = "Assignment-2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/imakshit/Assignment-2


<IPython.core.display.Javascript object>